wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0001
update_target:
  desc: null
  value: 40
