wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 32
epsilon_decay:
  desc: null
  value: 250
epsilon_end:
  desc: null
  value: 0.0
epsilon_start:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0002
memoery_size:
  desc: null
  value: 10000
network:
  desc: null
  value: Qnetwork
nn_nodes:
  desc: null
  value:
  - 64
  - 128
  - 2
update_target:
  desc: null
  value: 1000
